[project]
name = "rl2048"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numba>=0.61.2",
    "numpy>=2.2.5",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
]
